/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int TABLE = 6;
  /** RegularExpression Id. */
  int INSERT = 7;
  /** RegularExpression Id. */
  int INTO = 8;
  /** RegularExpression Id. */
  int VALUES = 9;
  /** RegularExpression Id. */
  int DROP = 10;
  /** RegularExpression Id. */
  int WHERE = 11;
  /** RegularExpression Id. */
  int FROM = 12;
  /** RegularExpression Id. */
  int SELECT = 13;
  /** RegularExpression Id. */
  int DISTINCT = 14;
  /** RegularExpression Id. */
  int ORDER = 15;
  /** RegularExpression Id. */
  int BY = 16;
  /** RegularExpression Id. */
  int PRIMARY = 17;
  /** RegularExpression Id. */
  int KEY = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int DOT = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int TEXT = 22;
  /** RegularExpression Id. */
  int NUM = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"DROP\"",
    "\"WHERE\"",
    "\"FROM\"",
    "\"SELECT\"",
    "\"DISTINCT\"",
    "\"ORDER\"",
    "\"BY\"",
    "\"PRIMARY\"",
    "\"KEY\"",
    "\"AND\"",
    "\".\"",
    "<ID>",
    "<TEXT>",
    "<NUM>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"*\"",
    "\"=\"",
  };

}
